### ISSUE TITLE
@types/glob breaks Typescript intellisense on non-node projects

### ISSUE THREAD

**Issue by leomeloxp** [sindresorhus/del#92] opened 2019-06-04 14:44 UTC
Hi,

I know this has been brought up in #88, #89 and #91 in some way but I feel like there hasn't been a suitable enough solution provided for this issue, so I'm raising this issue again.

I don't fully understand how `index.test-d.ts` works, but from what I could get, it helps validate/generate type defs for the library.

This is where I find this to be an issue though, if you're doing this to improve the developer experience of Typescript devs, by having @types/node added as a true dependency you're bloating intelissense for TS devs big time because when working on a browser based project now we also get suggestions for node APIs, and sometimes they are at the top of autocomplete suggestions because of auto import in VS Code.

<details>
    <summary>Example screenshot</summary>

![image](https://user-images.githubusercontent.com/266852/58887945-77a9f700-86de-11e9-8fc5-55acfd297026.png)

</details>

If the maintainers are willing to work on fixing this issue, I can try and help out and maybe provide a PR for it, but I would need some context as to why @types/glob can't "just" be made a devDep.

**Comment by sindresorhus** [comment] 2019-06-04 16:47
Duplicate of #88

**Comment by sindresorhus** [comment] 2019-06-04 16:47
> by having @types/node added as a true dependency you're bloating intelissense for TS devs big time because when working on a browser based project now we also get suggestions for node APIs

We are not adding `@types/node`. It's a dependency of `@types/glob`, which is maintained by https://github.com/DefinitelyTyped/DefinitelyTyped. You should complain there instead. There's nothing we can do about it here.

> but I would need some context as to why @types/glob can't "just" be made a devDep.

Because we depend on its type in the type definition: https://github.com/sindresorhus/del/blob/6e23f6ade68dcf5d9fc6be704fdc1deb8f95bf33/index.d.ts#L1

**Closed by sindresorhus** 2019-06-04 16:47 UTC
