### ISSUE TITLE
del.sync() doesn't delete files, returns empty array

### ISSUE THREAD

**Issue by tipleavalentin** [sindresorhus/del#94] opened 2019-07-05 07:33 UTC
del.sync([path]) returns [] and no file is deleted.

Windows 10 1903 x64 18362.207

**Comment by sindresorhus** [comment] 2019-07-05 07:38
Duplicate of #93

**Comment by sindresorhus** [comment] 2019-07-05 07:38
You didn't provide a lot of info, but I assume it's a duplicate.

**Closed by sindresorhus** 2019-07-05 07:38 UTC
