### ISSUE TITLE
Typing @types/glob as dependency

### ISSUE THREAD

**Issue by Skoucail** [sindresorhus/del#91] opened 2019-05-24 13:10 UTC
I'm building a browser application with gulp and the del npm package.
In the last version 4.1.1 "@types/glob": "^7.1.1" got added as a dependency.

In its turn "@types/glob": "^7.1.1" adds @types/node as a dependency.
For browser development this gives a lot of typing errors.

Examples:
.../node_modules/@types/node/module.d.ts(2,5): error TS2300: Duplicate identifier 'mod'.
.../node_modules/@types/requirejs/index.d.ts(38,11): error TS2300: Duplicate identifier 'mod'.
.../node_modules/@types/requirejs/index.d.ts(422,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'NodeRequire', but here has type 'Require'.

When using require in a TS file: error TS2554: Expected 1 arguments, but got 2

**Comment by sindresorhus** [comment] 2019-05-24 15:22
Duplicate of #88

**Closed by sindresorhus** 2019-05-24 15:22 UTC
