### ISSUE TITLE
Possible race condition with deleting files in directory

### ISSUE THREAD

**Issue by isiahmeadows** [sindresorhus/del#43] opened 2015-11-14 12:01 UTC
It's not a 100% repro, but occasionally, this fails to delete a directory from an error like this on my machine:

```js
// cwd: /home/me/project
del("folder/**").then(() => { /* ... */ })
```

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, lstat '/home/me/project/folder/file.js'
    at Error (native)
```

I'm running Ubuntu, by the way.

**Comment by schnittstabil** [comment] 2015-11-14 14:03
@impinball Thank you for reporting that. It is because we use `Promise.all` at the moment.
@sindresorhus You could assign me to fix it.

**Comment by sindresorhus** [comment] 2015-11-14 14:12
:+1:

**Comment by dgreene1** [comment] 2016-01-11 18:57
It looks like @schnittstabil has some kind of fix. Sorry for not being too familiar with forking, but will his solution join back up with the main del repository soon?

Thank you.

**Comment by schnittstabil** [comment] 2016-01-12 09:30
Sorry I cannot reproduce that bug anymore.
@isiahmeadows, @dgreene1: Are you still experiencing that problem?

**Comment by isiahmeadows** [comment] 2016-01-13 08:06
Not anymore.

**Comment by dgreene1** [comment] 2016-01-13 22:15
I see it about 1 in 10 times on my local dev machine. Our build server sees it pretty often. I think it's easier to recreate when you have multiple gulp tasks that are calling del since gulp is async.

Since it looks like there's already a fix from @schnittstabil, can we just get it pulled in @sindresorhus ?

**Comment by schnittstabil** [comment] 2016-01-14 05:34
@dgreene1 Would it be possible to provide us a stack trace?

As an interim solution you may want to use the fork in your `package.json` to  check out its validity:
```json
  "devDependencies": {
    "del": "github:schnittstabil/del#fix-race-condition"
  }
```

**Comment by schnittstabil** [comment] 2016-01-31 11:37
Ping @dgreene1.

I've tried `del` in async (multiple promises) and parallel (multiple processes) mode on hundreds of deeply nested files and folders,  without luck.

**Comment by schnittstabil** [comment] 2016-02-08 11:37
Not reproducible anymore. Closing, but please re-open if it still occurs.

**Closed by schnittstabil** 2016-02-08 11:37 UTC
Labels: bug, help wanted

**Comment by pizza2code** [comment] 2016-08-25 14:57
Have been receiving this error sporadically while using 2.2.1, just now reporting.  (I see the latest is 2.2.2 but it doesn't seem to address this issue?)  The ENOTEMPTY occurs 1 in 10 times as @dgreene1 mentioned, yet afterward I "ls -al" the dir and there aren't even hidden files inside.

Will be unable to use 'del' in our Gulp integration builds if it keeps failing unpredictably.

**Comment by schnittstabil** [comment] 2016-08-25 15:54
@pizza2code Would it be possible to provide us your gulpfile?

The most likely reasons causing `ENOTEMPTY`:
1. creation and deletion of files are running concurrently
2. another process creating files during deletion.

#### An example of 1.

```js
gulp.task('clean', function () {
  del('folder/**'); // missing 'return' !
});

gulp.task('default', ['clean'], function() {
  // create some files
});
```

#### An example of 2.:
A Finder instance may creating `.DS_Store` files during deletion for some reason (see https://github.com/sindresorhus/del/issues/42#issuecomment-155029166)

**Comment by pizza2code** [comment] 2016-08-26 17:38
You're right, it was a process creating files during deletion.  Sorry about that, and thanks for the help!

**Comment by nahtnam** [comment] 2017-09-01 07:50
Sorry, dont want to bring up an old thread but the ^ above was right. A process was creating files during the deletion. If you are making use of promises, make sure you `await` or use `.then()`. I forgot the `await` when the files were being created, so it quickly moved on to the deletion phase, rendering the issue.
